### ISSUE TITLE
doesnt work in windoz 7 pls halp

### ISSUE THREAD

**Issue by xClamintuzz** [Bestfast/Generatore_schede#9]
wut shold i open to mk dis work :PPPPP

**Comment by Bestfast** [comment]
You can use the precompiled binary(compiled by Semaphore CI) or you can build it yourself with mingw.

**Comment by xClamintuzz** [comment]
pls i rly lov dis program but doesnt work!!!!!! plz

**Comment by xClamintuzz** [comment]
mingw wat is dis

**Comment by Bestfast** [comment]
Check mingw.org.

**Comment by xClamintuzz** [comment]
doesnt clicc!!!!!!!

**Comment by Bestfast** [comment]
Copy&paste the link in your browser...

**Comment by xClamintuzz** [comment]
alright it just workd i only cliked open wit thankz :D

**Comment by Bestfast** [comment]
Np.
